Repository mul-meong/backend-utility, pull requests merged in 2024-11, with the labels that each got.

#5 [🚀 Utility] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
  src/main/java/com/mulmeong/utility/UtilityApplication.java
Labels: 👷 chore, 🚀 deploy

#3 [🔀 Utiltiy] 좋아요, 싫어요 기능 구현
  build.gradle
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/vo/DislikeRequestVo.java
  src/main/java/com/mulmeong/utility/adapter/in/web/vo/LikesRequestVo.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/entity/DislikeEntity.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/entity/LikesEntity.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/mapper/DislikeEntityMapper.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/mapper/LikesEntityMapper.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/DislikeMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/DislikeRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/LikesMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/LikesRepository.java
  src/main/java/com/mulmeong/utility/application/mapper/DislikeDtoMapper.java
  src/main/java/com/mulmeong/utility/application/mapper/LikesDtoMapper.java
  src/main/java/com/mulmeong/utility/application/port/in/DislikeUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/LikesUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/DislikeRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/LikesRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/out/DislikePort.java
  src/main/java/com/mulmeong/utility/application/port/out/LikesPort.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/DislikeEntityResponseDto.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/DislikeResponseDto.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/LikesEntityResponseDto.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/LikesResponseDto.java
  src/main/java/com/mulmeong/utility/application/service/DislikeService.java
  src/main/java/com/mulmeong/utility/application/service/LikesService.java
  src/main/java/com/mulmeong/utility/common/exception/BaseException.java
  src/main/java/com/mulmeong/utility/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/utility/common/response/BaseResponse.java
  src/main/java/com/mulmeong/utility/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/utility/domain/model/Dislike.java
  src/main/java/com/mulmeong/utility/domain/model/Likes.java
Labels: ✨ enhancement

#9 [🔀 Utility] 좋아요, 싫어요 한 피드, 쇼츠 조회 기능 구현
  build.gradle
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/vo/DislikeRequestVo.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/mapper/DislikeEntityMapper.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/DislikeMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/DislikeRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/LikesMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/LikesRepository.java
  src/main/java/com/mulmeong/utility/application/mapper/DislikeDtoMapper.java
  src/main/java/com/mulmeong/utility/application/mapper/LikesDtoMapper.java
  src/main/java/com/mulmeong/utility/application/port/in/DislikeUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/LikesUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/DislikeListRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/LikesListRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/out/DislikePort.java
  src/main/java/com/mulmeong/utility/application/port/out/LikesPort.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/LikesResponseDto.java
  src/main/java/com/mulmeong/utility/application/service/DislikeService.java
  src/main/java/com/mulmeong/utility/application/service/LikesService.java
Labels: ✨ enhancement

#10 [🔀 Utility] 피드 북마크 기능 구현
  build.gradle
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/BookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/vo/FeedBookmarkRequestVo.java
  src/main/java/com/mulmeong/utility/adapter/in/web/vo/ShortsBookmarkRequestVo.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/entity/FeedBookmarkEntity.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/entity/ShortsBookmarkEntity.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/mapper/BookmarkEntityMapper.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/bookmarkRepository/BookmarkRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/bookmarkRepository/FeedBookmarkMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/bookmarkRepository/ShortsBookmarkMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/dislikeRepository/DislikeMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/dislikeRepository/DislikeRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/likesRepository/LikesMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/likesRepository/LikesRepository.java
  src/main/java/com/mulmeong/utility/application/mapper/BookmarkDtoMapper.java
  src/main/java/com/mulmeong/utility/application/port/in/BookmarkUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/BookmarkRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/out/BookmarkPort.java
  src/main/java/com/mulmeong/utility/application/port/out/dto/BookmarkResponseDto.java
  src/main/java/com/mulmeong/utility/application/service/BookmarkService.java
  src/main/java/com/mulmeong/utility/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/utility/domain/model/Bookmark.java
Labels: ✨ enhancement

#13 [🔀 Utility] 좋아요 한 피드, 쇼츠 페이지네이션 기능 구현
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/BookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/likesRepository/LikesMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/likesRepository/LikesRepository.java
  src/main/java/com/mulmeong/utility/application/port/in/LikesUseCase.java
  src/main/java/com/mulmeong/utility/application/port/out/LikesPort.java
  src/main/java/com/mulmeong/utility/application/service/LikesService.java
Labels: ✨ enhancement

#14 [🔀 Utility] 팔로우 기능 구현
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/FollowController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/entity/FollowEntity.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/mapper/FollowEntityMapper.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/FollowRepository/FollowMongoRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/FollowRepository/FollowRepository.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/likesRepository/LikesRepository.java
  src/main/java/com/mulmeong/utility/application/port/in/FollowUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/LikesUseCase.java
  src/main/java/com/mulmeong/utility/application/port/in/dto/FollowRequestDto.java
  src/main/java/com/mulmeong/utility/application/port/out/FollowPort.java
  src/main/java/com/mulmeong/utility/application/port/out/LikesPort.java
  src/main/java/com/mulmeong/utility/application/service/FollowService.java
  src/main/java/com/mulmeong/utility/application/service/LikesService.java
  src/main/java/com/mulmeong/utility/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/utility/common/response/BaseResponse.java
  src/main/java/com/mulmeong/utility/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/utility/domain/model/Follow.java
Labels: ✨ enhancement

#17 [🔀 Utility] Swagger 추가
  build.gradle
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/BookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/FollowController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
  src/main/java/com/mulmeong/utility/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/utility/common/health/HealthCheckController.java
Labels: ✨ enhancement

#20 [🚑️ Utiltiy] 회원기능 uri auth/ 추가
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthFollowController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/BookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/DislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/FollowController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/LikesController.java
Labels: 🚑️ hotfix

#23 [🚑️ Utility] 북마크 상태 조회 추가
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthBookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthDislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthFollowController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthLikesController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/FollowController.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/bookmarkRepository/BookmarkRepository.java
  src/main/java/com/mulmeong/utility/application/port/in/BookmarkUseCase.java
  src/main/java/com/mulmeong/utility/application/port/out/BookmarkPort.java
  src/main/java/com/mulmeong/utility/application/service/BookmarkService.java
Labels: 🚑️ hotfix

#25 [🚑️ Utility] @SpringBootTest 주석 처리
  src/test/java/com/mulmeong/utility/UtilityApplicationTests.java
Labels: 🐛 bug

#26 [🚑️ Utility] config 의존성 추가
  build.gradle
Labels: 🐛 bug

#22 [🚑️ Utility] 북마크 상태 조회 추가
  build.gradle
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthBookmarkController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthDislikeController.java
  src/main/java/com/mulmeong/utility/adapter/in/web/controller/AuthLikesController.java
  src/main/java/com/mulmeong/utility/adapter/out/infrastructure/mongo/repository/bookmarkRepository/BookmarkRepository.java
  src/main/java/com/mulmeong/utility/application/port/in/BookmarkUseCase.java
  src/main/java/com/mulmeong/utility/application/port/out/BookmarkPort.java
  src/main/java/com/mulmeong/utility/application/service/BookmarkService.java
  src/test/java/com/mulmeong/utility/UtilityApplicationTests.java
Labels: 🚑️ hotfix
